# 快捷命令配置文件
# 格式：命令名 脚本路径
# 生成时间：2026年 04月 01日 星期三 23:26:39 CST
# 可以手动编辑此文件来添加/修改快捷命令

ins /vol1/1000/shell/service-tools/service-install.sh
un /vol1/1000/shell/service-tools/service-uninstall.sh
wb /vol1/1000/shell/service-tools/wb.sh
ge /vol1/1000/shell/service-tools/shortcut.sh
mn /vol1/1000/shell/service-tools/menu-generate.sh
