SERVICE_NAME="wb"
SERVICE_DESC="wb 服务"
RUN_USER="shissx"
RUN_GROUP="Users"
WORK_DIR="/vol1/1000/shell/service-tools"
EXEC_PATH="/vol1/1000/shell/service-tools/venv/bin/python3 /vol1/1000/shell/service-tools/wb.py"
MOUNT_PATH="/vol1/1000/shell"
PYTHON_PATH="/vol1/1000/shell/service-tools/venv/bin/python3"
